{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jarc-project2-chart.serviceAccountName" . }}
  labels:
    {{- include "jarc-project2-chart.labels" . | nindent 4 }}
    {{ toYaml .Values.labels | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
