apiVersion: v1
kind: Service
metadata:
  name: {{ include "jarc-project2-chart.fullname" . }}
  labels:
    {{- include "jarc-project2-chart.labels" . | nindent 4 }}
    {{ toYaml .Values.labels | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  selector:
    {{- include "jarc-project2-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: nclouds-svc
  type: {{ .Values.service.type }}